# Generated by Django 5.2 on 2025-04-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetiteur',
            name='competences',
        ),
        migrations.RemoveField(
            model_name='repetiteur',
            name='formations',
        ),
    ]
