# Generated by Django 5.2 on 2025-04-12 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_repetiteur_competences_and_more'),
        ('repetiteurs', '0001_initial'),
        ('souscripteurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscription',
            name='repetiteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repetiteurs.repetiteur'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='repetiteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repetiteurs.repetiteur'),
        ),
        migrations.AlterField(
            model_name='souscription',
            name='souscripteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souscripteurs.souscripteur'),
        ),
        migrations.DeleteModel(
            name='Repetiteur',
        ),
        migrations.DeleteModel(
            name='Souscripteur',
        ),
    ]
