# Generated by Django 5.2 on 2025-06-01 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('repetiteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='Aucune description')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='Aucune description')),
                ('duree', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OffreTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Primaire 1ère-5ème, Collège par matière', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_offre', models.CharField(choices=[('forfait_global', 'Forfait Global'), ('par_matiere', 'Par Matière'), ('pack_specialite', 'Pack Spécialité'), ('pack_examen', 'Pack Examen')], max_length=20)),
                ('prix_unitaire', models.IntegerField(help_text='Prix en GNF')),
                ('prix_combine', models.IntegerField(blank=True, help_text='Prix si plusieurs matières combinées', null=True)),
                ('nombre_seances_mois', models.IntegerField(default=12, help_text='Nombre de séances par mois')),
                ('duree_seance_max', models.IntegerField(default=180, help_text="Durée max d'une séance en minutes")),
                ('jours_par_semaine', models.IntegerField(default=3, help_text='Nombre de jours par semaine')),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('matieres_incluses', models.ManyToManyField(blank=True, help_text="Matières incluses dans l'offre", related_name='offres_tarifaires', to='repetiteurs.cours')),
                ('niveaux', models.ManyToManyField(related_name='offres_tarifaires', to='core.niveau')),
            ],
            options={
                'verbose_name': 'Offre Tarifaire',
                'verbose_name_plural': 'Offres Tarifaires',
                'ordering': ['ordre', 'prix_unitaire'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], max_length=20)),
                ('methode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='paiements.methodepaiement')),
            ],
        ),
    ]
