# Generated by Django 5.2 on 2025-05-31 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiements', '0001_initial'),
        ('souscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='souscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='souscriptions.souscription'),
        ),
    ]
