# Generated by Django 5.2 on 2025-05-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantarifaire',
            name='description',
            field=models.TextField(blank=True, default='Aucune description'),
        ),
        migrations.AddField(
            model_name='plantarifaire',
            name='duree',
            field=models.IntegerField(default=0, help_text='Durée en jours'),
        ),
    ]
