# Generated by Django 5.2 on 2025-05-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_plantarifaire_description_plantarifaire_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodepaiement',
            name='description',
            field=models.TextField(blank=True, default='Aucune description'),
        ),
        migrations.AlterField(
            model_name='plantarifaire',
            name='duree',
            field=models.IntegerField(default=0),
        ),
    ]
