# Generated by Django 5.2 on 2025-05-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adresse',
            field=models.CharField(max_length=100),
        ),
    ]
