# Generated by Django 5.2 on 2025-05-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'Ce numéro de téléphone est déjà utilisé.'}, max_length=30, null=True, unique=True),
        ),
    ]
