# Generated by Django 5.2 on 2025-05-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'blank': 'Ce champ ne peut pas être vide.', 'null': 'Ce champ ne peut pas être nul.', 'unique': 'Cette adresse e-mail est déjà utilisée.'}, max_length=100, null=True, unique=True),
        ),
    ]
