# Generated by Django 5.2 on 2025-05-14 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repetiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/repetiteurs/')),
                ('biographie', models.TextField(blank=True, null=True)),
                ('competences', models.ManyToManyField(blank=True, related_name='repetiteurs', to='repetiteurs.competence')),
                ('cours', models.ManyToManyField(blank=True, related_name='repetiteurs', to='repetiteurs.cours')),
                ('formations', models.ManyToManyField(blank=True, related_name='repetiteurs', to='formations.formation')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repetiteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
