# Generated by Django 5.2 on 2025-04-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_repetiteur_competences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repetiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/repetiteurs/')),
                ('competences', models.ManyToManyField(to='core.competence')),
                ('formations', models.ManyToManyField(to='core.typeformation')),
            ],
        ),
    ]
