# Generated by Django 5.2 on 2025-05-02 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repetiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/repetiteurs/')),
                ('biographie', models.TextField(blank=True, null=True)),
                ('competences', models.ManyToManyField(blank=True, null=True, related_name='repetiteurs', to='repetiteurs.competence')),
                ('formations', models.ManyToManyField(blank=True, null=True, related_name='repetiteurs', to='formations.formation')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repetiteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='core.niveau')),
                ('repetiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='repetiteurs.repetiteur')),
            ],
        ),
    ]
