# Generated by Django 5.2 on 2025-05-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetiteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetiteur',
            name='cgu_acceptees',
            field=models.BooleanField(default=False),
        ),
    ]
