# Generated by Django 5.2 on 2025-05-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repetiteurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetiteur',
            name='competences',
        ),
    ]
