# Generated by Django 5.2 on 2025-04-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_remove_formation_repetiteurs'),
        ('repetiteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetiteur',
            name='formations',
            field=models.ManyToManyField(related_name='repetiteurs', to='formations.formation'),
        ),
    ]
