# Generated by Django 5.2 on 2025-05-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repetiteurs', '0002_remove_repetiteur_competences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetiteur',
            name='niveaux',
        ),
    ]
