# Generated by Django 5.2 on 2025-05-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiements', '0001_initial'),
        ('repetiteurs', '0001_initial'),
        ('souscripteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], max_length=20)),
                ('cours', models.ManyToManyField(related_name='souscriptions', to='repetiteurs.cours')),
                ('plan_tarifaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='paiements.plantarifaire')),
                ('repetiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='repetiteurs.repetiteur')),
                ('souscripteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='souscripteurs.souscripteur')),
            ],
        ),
        migrations.CreateModel(
            name='PasserSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('souscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='souscriptions.souscription')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('souscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='souscriptions.souscription')),
            ],
        ),
    ]
