# Generated by Django 5.2 on 2025-05-30 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('paiements', '0001_initial'),
        ('repetiteurs', '0001_initial'),
        ('souscripteurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSouscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enfants', models.PositiveIntegerField()),
                ('creneaux_preferes', models.JSONField(default=list, help_text='Liste des créneaux préférés')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('affectée', 'Affectée'), ('rejetée', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('matieres', models.ManyToManyField(related_name='demandes', to='repetiteurs.cours')),
                ('moyen_paiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiements.methodepaiement')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.niveau')),
                ('offre_tarifaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiements.offretarifaire')),
                ('souscripteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='souscripteurs.souscripteur')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='active', max_length=20)),
                ('seances_prevues', models.IntegerField(help_text='Nombre total de séances prévues')),
                ('seances_effectuees', models.IntegerField(default=0, help_text='Nombre de séances effectuées')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ManyToManyField(related_name='souscriptions', to='repetiteurs.cours')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('demande_origine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souscription_creee', to='souscriptions.demandesouscription')),
                ('moyen_paiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiements.methodepaiement')),
                ('offre_tarifaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='paiements.offretarifaire')),
                ('repetiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='repetiteurs.repetiteur')),
                ('souscripteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='souscripteurs.souscripteur')),
            ],
        ),
        migrations.CreateModel(
            name='PasserSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('souscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='souscriptions.souscription')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('souscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='souscriptions.souscription')),
            ],
        ),
    ]
