# Generated by Django 5.2 on 2025-05-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('paiements', '0002_initial'),
        ('repetiteurs', '0001_initial'),
        ('souscripteurs', '0001_initial'),
        ('souscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSouscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enfants', models.PositiveIntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('affectée', 'Affectée'), ('rejetée', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('matieres', models.ManyToManyField(related_name='demandes', to='repetiteurs.cours')),
                ('moyen_paiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiements.methodepaiement')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.niveau')),
                ('souscripteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='souscripteurs.souscripteur')),
            ],
        ),
    ]
