# Generated by Django 5.2 on 2025-05-23 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_initial'),
        ('souscriptions', '0002_demandesouscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscription',
            name='plan_tarifaire',
        ),
        migrations.AddField(
            model_name='souscription',
            name='moyen_paiement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiements.methodepaiement'),
        ),
    ]
