# Generated by Django 5.2 on 2025-04-13 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        ('repetiteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='repetiteurs',
            field=models.ManyToManyField(related_name='formations', to='repetiteurs.repetiteur'),
        ),
        migrations.AddField(
            model_name='formation',
            name='type_formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='formations.typeformation'),
        ),
    ]
